services:
  api-side:
    image: the80hz/awg-pinger:api-side
    build:
      context: .
      target: api-side
    container_name: awg-pinger-api-side
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./api-data:/app/api-data:ro
    environment:
      CLIENTS_PATH: /app/api-data/clients.json
      TELEGRAM_CONFIG_PATH: /app/api-data/telegram.json

  awg-client-side:
    image: the80hz/awg-pinger:awg-client-side
    build:
      context: .
      target: awg-client-side
    container_name: awg-pinger-awg-client-side
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: "1"
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./data:/app/data:ro
    environment:
      SETTINGS_PATH: /app/data/settings.json
      TUNNEL_QUICK_CMD: awg-quick
      WG_QUICK_USERSPACE_IMPLEMENTATION: amneziawg-go
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
